services:
  app:
    build:
      context: .
      dockerfile: tezdoc/Dockerfile
    container_name: hackatonCo-b_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - hackatonCo-b
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: hackatonCo-b_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackatonCo_b
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - "3321:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - hackatonCo-b

  nginx:
    image: nginx:alpine
    container_name: hackatonCo-b_nginx
    ports:
      - "8021:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    depends_on:
      - app
    networks:
      - hackatonCo-b

volumes:
  dbdata:

networks:
  hackatonCo-b:
